### ISSUE TITLE
non-composer version

### ISSUE THREAD

**Issue by vico93** [Seklfreak/youtube-search-feed#1]
Hi! Is possible to make a version without the need of composer?

I'm in xampp (win10) and having trouble trying to download the dependencies using php-downloader.com

**Comment by Seklfreak** [comment]
I ran `composer install` on a clean clone and zipped it for you. This should work out of the box. :) 

[youtube-search-feed.zip](https://github.com/Seklfreak/youtube-search-feed/files/1503783/youtube-search-feed.zip)

Please report back if it works, so I can close the issue.

**Comment by vico93** [comment]
Thanks a lot for this!
