### ISSUE TITLE
Error 500 when running the script on a Rpi with apache 2 and PHP 7

### ISSUE THREAD

**Issue by vico93** [Seklfreak/youtube-search-feed#2]
I dont know what i did wrong.
I'm on a rPi3 and installed the Apache + PHP using [this tutorial](https://projects.raspberrypi.org/en/projects/lamp-web-server-with-wordpress) (i didnt complete this - stopped on php part - and replace php5 by php7.0)
Using the exact same folder structure and query under [this version of xampp](https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/7.1.11/) works fine.

**Comment by Seklfreak** [comment]
Can you check the log files for errors?

**Comment by vico93** [comment]
I'm kind of rusty in web server these days. Can you tell me where to get them?

**Comment by Seklfreak** [comment]
I don't use XAMPP, but I found this googling it: https://stackoverflow.com/a/3719566 

On Ubuntu you might find them at `/var/log/php_errors.log` or `/var/log/apache2/error.log` or something similar.

**Comment by vico93** [comment]
Gotcha! https://gist.github.com/vpontin/899e1d312c6dcbbec94a5bbe06d50e7c

**Comment by Seklfreak** [comment]
Try installing curl.

Should be `sudo apt-get install php-curl` on ubuntu.

**Comment by vico93** [comment]
Installed here, but via SSH, i will only be able to test wherever the script works tomorrow.

**Comment by vico93** [comment]
After installed php-curl i got this error:

https://gist.github.com/vpontin/cd8f09fe8fdd0e5b61928914d6f39fe3

**EDIT**: This was fixed by installing the package `php-xml`, now generates the feed. Thanks for the help!
